services:
  postgres:
      image: 'postgres:latest'
      container_name: delphi-postgres
      env_file:
        - .env
      ports:
        - '5432:5432'
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
  redis:
      image: 'redis:latest'
      container_name: delphi-redis
      ports:
        - '6379:6379'
      volumes:
        - ./redis_data:/data
  # rabbitmq:
  #   # image: rabbitmq:3-management
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   env_file:
  #     - .env
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #     - 61613:61613
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - "./backend:/backend"
    # env_file:
    #   - ./diamond-backend/diamond/.env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data: